#spring config
spring:
  application:
    name: salon
  data:
    mongodb:
      username:
      password:
      uri: mongodb://localhost:27017/salon

#server config
server:
  port: 8081

jwt:
  secret: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkQgWiIsImFkbWluIjp0cnVlLCJpYXQiOjE1MTYyMzkwMjJ9.3Dre1XXWiCiQnhINIWT2vfvnBjzbkqmWQD-tdO9qTQI